//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26919.1
// 
namespace PiFormance.Client.Cpu {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CpuSample", Namespace="http://schemas.datacontract.org/2004/07/PiFormance.Services.CpuRelated")]
    public partial class CpuSample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PiFormance.Client.Cpu.Frequency ClockSpeedField;
        
        private System.Collections.ObjectModel.ObservableCollection<PiFormance.Client.Cpu.Core> CoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.Frequency ClockSpeed {
            get {
                return this.ClockSpeedField;
            }
            set {
                if ((object.ReferenceEquals(this.ClockSpeedField, value) != true)) {
                    this.ClockSpeedField = value;
                    this.RaisePropertyChanged("ClockSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PiFormance.Client.Cpu.Core> Cores {
            get {
                return this.CoresField;
            }
            set {
                if ((object.ReferenceEquals(this.CoresField, value) != true)) {
                    this.CoresField = value;
                    this.RaisePropertyChanged("Cores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frequency", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.FrequencyQuantity")]
    public partial class Frequency : PiFormance.Client.Cpu.PhysicalQuantityOfFrequency9McGUATy {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Core", Namespace="http://schemas.datacontract.org/2004/07/PiFormance.Services.CpuRelated")]
    public partial class Core : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private PiFormance.Client.Cpu.Load LoadField;
        
        private PiFormance.Client.Cpu.ThermalReading TemperatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.Load Load {
            get {
                return this.LoadField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadField, value) != true)) {
                    this.LoadField = value;
                    this.RaisePropertyChanged("Load");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.ThermalReading Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.TemperatureField, value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bindable", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Notification")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.PhysicalQuantityOfRatioP6CKV5DK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Ratio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Load))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.PhysicalQuantityOfTemperaturemklq4rKt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Temperature))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.ThermalReading))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.PhysicalQuantityOfMemory_STgboZd0))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Memory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.PhysicalQuantityOfFrequency9McGUATy))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Frequency))]
    public partial class Bindable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, object> _propertyFieldDictionaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, object> _propertyFieldDictionary {
            get {
                return this._propertyFieldDictionaryField;
            }
            set {
                if ((object.ReferenceEquals(this._propertyFieldDictionaryField, value) != true)) {
                    this._propertyFieldDictionaryField = value;
                    this.RaisePropertyChanged("_propertyFieldDictionary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhysicalQuantityOfRatioP6CKV5DK", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Ratio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Load))]
    public partial class PhysicalQuantityOfRatioP6CKV5DK : PiFormance.Client.Cpu.Bindable {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ratio", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.RatioQuantity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Load))]
    public partial class Ratio : PiFormance.Client.Cpu.PhysicalQuantityOfRatioP6CKV5DK {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Load", Namespace="http://schemas.datacontract.org/2004/07/PiFormance.Services.CpuRelated")]
    public partial class Load : PiFormance.Client.Cpu.Ratio {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhysicalQuantityOfTemperaturemklq4rKt", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Temperature))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.ThermalReading))]
    public partial class PhysicalQuantityOfTemperaturemklq4rKt : PiFormance.Client.Cpu.Bindable {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temperature", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.TemperatureQuantit" +
        "y")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.ThermalReading))]
    public partial class Temperature : PiFormance.Client.Cpu.PhysicalQuantityOfTemperaturemklq4rKt {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThermalReading", Namespace="http://schemas.datacontract.org/2004/07/PiFormance.Services.CpuRelated")]
    public partial class ThermalReading : PiFormance.Client.Cpu.Temperature {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhysicalQuantityOfMemory_STgboZd0", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Memory))]
    public partial class PhysicalQuantityOfMemory_STgboZd0 : PiFormance.Client.Cpu.Bindable {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Memory", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.MemoryQuantity")]
    public partial class Memory : PiFormance.Client.Cpu.PhysicalQuantityOfMemory_STgboZd0 {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhysicalQuantityOfFrequency9McGUATy", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Frequency))]
    public partial class PhysicalQuantityOfFrequency9McGUATy : PiFormance.Client.Cpu.Bindable {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RamUsage", Namespace="http://schemas.datacontract.org/2004/07/PiFormance.Services.CpuRelated")]
    public partial class RamUsage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PiFormance.Client.Cpu.Memory AvailableMemoryField;
        
        private PiFormance.Client.Cpu.Memory TotalMemoryField;
        
        private PiFormance.Client.Cpu.Ratio UsageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.Memory AvailableMemory {
            get {
                return this.AvailableMemoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableMemoryField, value) != true)) {
                    this.AvailableMemoryField = value;
                    this.RaisePropertyChanged("AvailableMemory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.Memory TotalMemory {
            get {
                return this.TotalMemoryField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalMemoryField, value) != true)) {
                    this.TotalMemoryField = value;
                    this.RaisePropertyChanged("TotalMemory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PiFormance.Client.Cpu.Ratio Usage {
            get {
                return this.UsageField;
            }
            set {
                if ((object.ReferenceEquals(this.UsageField, value) != true)) {
                    this.UsageField = value;
                    this.RaisePropertyChanged("Usage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitOfRatioP6CKV5DK", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.BaseUnitOfRatioP6CKV5DK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Whole))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Percent))]
    public partial class UnitOfRatioP6CKV5DK : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseUnitOfRatioP6CKV5DK", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Whole))]
    public partial class BaseUnitOfRatioP6CKV5DK : PiFormance.Client.Cpu.UnitOfRatioP6CKV5DK {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Whole", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.RatioQuantity")]
    public partial class Whole : PiFormance.Client.Cpu.BaseUnitOfRatioP6CKV5DK {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Percent", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.RatioQuantity")]
    public partial class Percent : PiFormance.Client.Cpu.UnitOfRatioP6CKV5DK {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitOfTemperaturemklq4rKt", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.BaseUnitOfTemperaturemklq4rKt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Celsius))]
    public partial class UnitOfTemperaturemklq4rKt : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseUnitOfTemperaturemklq4rKt", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.Definitions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PiFormance.Client.Cpu.Celsius))]
    public partial class BaseUnitOfTemperaturemklq4rKt : PiFormance.Client.Cpu.UnitOfTemperaturemklq4rKt {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Celsius", Namespace="http://schemas.datacontract.org/2004/07/Core.Common.Quantities.TemperatureQuantit" +
        "y")]
    public partial class Celsius : PiFormance.Client.Cpu.BaseUnitOfTemperaturemklq4rKt {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cpu.ICpuService", CallbackContract=typeof(PiFormance.Client.Cpu.ICpuServiceCallback))]
    public interface ICpuService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBaseOf_ICpuCallback/Acknowledge")]
        System.Threading.Tasks.Task AcknowledgeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICpuServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICpuService/CpuChanged")]
        void CpuChanged(PiFormance.Client.Cpu.CpuSample cpuSample);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICpuService/RamUsageChanged")]
        void RamUsageChanged(PiFormance.Client.Cpu.RamUsage ramUsage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICpuServiceChannel : PiFormance.Client.Cpu.ICpuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CpuServiceClientBase : System.ServiceModel.DuplexClientBase<PiFormance.Client.Cpu.ICpuService>, PiFormance.Client.Cpu.ICpuService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CpuServiceClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, CpuServiceClientBase.GetDefaultBinding(), CpuServiceClientBase.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_ICpuService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CpuServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, CpuServiceClientBase.GetBindingForEndpoint(endpointConfiguration), CpuServiceClientBase.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CpuServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, CpuServiceClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CpuServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, CpuServiceClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CpuServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task AcknowledgeAsync() {
            return base.Channel.AcknowledgeAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ICpuService)) {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ICpuService)) {
                return new System.ServiceModel.EndpointAddress(new System.Uri("net.tcp://localhost:8733/PiFormance/"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return CpuServiceClientBase.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_ICpuService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return CpuServiceClientBase.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_ICpuService);
        }
        
        public enum EndpointConfiguration {
            
            NetTcpBinding_ICpuService,
        }
    }
    
    public class CpuChangedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CpuChangedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PiFormance.Client.Cpu.CpuSample cpuSample {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PiFormance.Client.Cpu.CpuSample)(this.results[0]));
            }
        }
    }
    
    public class RamUsageChangedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RamUsageChangedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PiFormance.Client.Cpu.RamUsage ramUsage {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PiFormance.Client.Cpu.RamUsage)(this.results[0]));
            }
        }
    }
    
    public partial class CpuServiceClient : CpuServiceClientBase {
        
        public CpuServiceClient(EndpointConfiguration endpointConfiguration) : 
                this(new CpuServiceClientCallback(), endpointConfiguration) {
        }
        
        private CpuServiceClient(CpuServiceClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration) {
            callbackImpl.Initialize(this);
        }
        
        public CpuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new CpuServiceClientCallback(), binding, remoteAddress) {
        }
        
        private CpuServiceClient(CpuServiceClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress) {
            callbackImpl.Initialize(this);
        }
        
        public CpuServiceClient() : 
                this(new CpuServiceClientCallback()) {
        }
        
        private CpuServiceClient(CpuServiceClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl)) {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<CpuChangedReceivedEventArgs> CpuChangedReceived;
        
        public event System.EventHandler<RamUsageChangedReceivedEventArgs> RamUsageChangedReceived;
        
        private void OnCpuChangedReceived(object state) {
            if ((this.CpuChangedReceived != null)) {
                object[] results = ((object[])(state));
                this.CpuChangedReceived(this, new CpuChangedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnRamUsageChangedReceived(object state) {
            if ((this.RamUsageChangedReceived != null)) {
                object[] results = ((object[])(state));
                this.RamUsageChangedReceived(this, new RamUsageChangedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class CpuServiceClientCallback : object, ICpuServiceCallback {
            
            private CpuServiceClient proxy;
            
            public void Initialize(CpuServiceClient proxy) {
                this.proxy = proxy;
            }
            
            public void CpuChanged(PiFormance.Client.Cpu.CpuSample cpuSample) {
                this.proxy.OnCpuChangedReceived(new object[] {
                            cpuSample});
            }
            
            public void RamUsageChanged(PiFormance.Client.Cpu.RamUsage ramUsage) {
                this.proxy.OnRamUsageChangedReceived(new object[] {
                            ramUsage});
            }
        }
    }
}
